version: '3.1'

services:
  backend:
    build:
      dockerfile: ./backend/Dockerfile
      context: .
    ports:
      - 8000:80
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/
      - SCHEDULER_URL=http://scheduler
  scheduler:
    build:
      dockerfile: ./scheduler/Dockerfile
      context: .
    ports:
      - 8001:80
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
    ports:
      - 8002:80
    environment:
      - SCHEDULER_URL=http://scheduler
      - BACKEND_URL=http://backend
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
